# Generated by Django 3.0.4 on 2020-04-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=4, max_digits=8)),
                ('image', models.ImageField(upload_to='images/')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
