# Generated by Django 3.0.4 on 2020-03-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_auto_20200324_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=4, max_digits=8)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Departamento')),
            ],
        ),
    ]
