# Generated by Django 3.0.4 on 2020-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
