# Generated by Django 3.0.4 on 2020-03-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_remove_post_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
