# Generated by Django 3.0.4 on 2020-03-31 13:25

import aplicacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aplicacao.models.upload_image_path),
        ),
    ]
